### ISSUE TITLE
Add logic for walls

### ISSUE THREAD

**Issue by lukehedger** [lukehedger/quoridor#5]
### Tasks
- [x] Display walls to right of board
- [x] Click a wall to "select"
- [ ] Then click a square to place wall (over that square, to the bottom and one to right)
- [ ] Don't allow wall clicks on extreme squares
- [ ] Click wall again to flip to vertical, and again to horizontal (need to monitor clicks)
- [x] Click wall on right again to "deselect"
- [ ] Prevent wall from being moved again once placed
- [ ] Don't allow pawns to move through walls
- [ ] Count a wall place as "make move" - use `endMove`?
- [ ] Only allow each player to place maximum of 10 walls

### Rules
- There are 20 walls in total in a game
- Walls are split equally among players - so in a 2 player game each players gets 10 walls
- Walls are 2 squares long can be placed in the 'groove' exactly across 2 squares
- Pawns cannot move 'through' walls - they must go around
- A move consists of _either_ moving a piece or placing a wall - not both
- Walls cannot be moved once placed
- A wall cannot be placed in a position that would cut off the only remaining path to the side of the board a pawn must reach to win
- [See notation for walls](https://en.wikipedia.org/wiki/Quoridor#Notation)
